services:
  user-service:
    build: ./user_service
    container_name: user-service
    ports:
      - "5001:5001"
    networks:
      - microservices-network
    restart: unless-stopped

  order-service:
    build: ./order_service
    container_name: order-service
    ports:
      - "5002:5002"
    networks:
      - microservices-network
    restart: unless-stopped

  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit-dashboard
    ports:
      - "8501:8501"
    environment:
      - USER_SERVICE_URL=http://user-service:5001
      - ORDER_SERVICE_URL=http://order-service:5002
    depends_on:
      - user-service
      - order-service
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge 

